---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: birds-fe-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ripleymj.cluster.jmunixusers.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: birds-app-front-end-service
                port:
                  number: 80
