---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: birds-be-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ripleymj.cluster.jmunixusers.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: birds-app-back-end-service
                port:
                  number: 8080
